yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="index"),
    path("group/<slug:slug>/", views.group_posts, name="group_list"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("posts/<int:post_id>/", views.post_detail, name="post_detail"),
    path("create/", views.post_create, name="post_create"),
    path("posts/<int:post_id>/edit/", views.post_edit, name="post_edit"),
    path("posts/<int:post_id>/comment", views.add_comment, name="add_comment"),
    path("follow/", views.follow_index, name="follow_index"),
    path("profile/<str:username>/follow/",
         views.profile_follow,
         name="profile_follow"),
    path(
        "profile/<str:username>/unfollow/",
        views.profile_unfollow,
        name="profile_unfollow",
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/includes/header.html
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        {% load static %}
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      {# Добавлено в спринте #}

      {% comment %}
      Меню - список пунктов со стандартными классами Bootsrap.
      Класс nav-pills нужен для выделения активных пунктов
      {% endcomment %}
      <ul class="nav nav-pills">
        {% with request.resolver_match.view_name as view_name %}
        <li class="nav-item">
          <a class="nav-link
             {% if view_name  == 'about:author' %}
               active
             {% endif %}"
             href="{% url 'about:author' %}">
            Об авторе
          </a>
        </li>
        {% endwith %}
        {% with request.resolver_match.view_name as view_name %}
        <li class="nav-item">
          <a class="nav-link
             {% if view_name  == 'about:tech' %}
               active
             {% endif %}"
             href="{% url 'about:tech' %}">
            Технологии
          </a>
        </li>
        {% endwith %}

        {% if user.is_authenticated %}

        {% with request.resolver_match.view_name as view_name %}
        <li class="nav-item">
          <a class="nav-link
             {% if view_name  == 'posts:post_create' %}
               active
             {% endif %}"
             href="{% url 'posts:post_create' %}">
            Новая запись
          </a>
        </li>
        {% endwith %}

        {% with request.resolver_match.view_name as view_name %}
        <li class="nav-item">
          <a class="nav-link
             {% if view_name  == 'users:password_change' %}
               active
             {% endif %}"
             href="{% url 'users:password_change' %}">
            Изменить пароль
          </a>
        </li>
        {% endwith %}

        {% with request.resolver_match.view_name as view_name %}
        <li class="nav-item">
          <a class="nav-link
             {% if view_name  == 'users:logout' %}
               active
             {% endif %}"
             href="{% url 'users:logout' %}">
            Выйти
          </a>
        </li>
        {% endwith %}

        <li>
          Пользователь: {{ user.username }}
        <li>
        {% else %}

        {% with request.resolver_match.view_name as view_name %}
        <li class="nav-item">
          <a class="nav-link
             {% if view_name  == 'users:login' %}
               active
             {% endif %}"
             href="{% url 'users:login' %}">
            Войти
          </a>
        </li>
        {% endwith %}

        {% with request.resolver_match.view_name as view_name %}
        <li class="nav-item">
          <a class="nav-link
             {% if view_name  == 'users:signup' %}
               active
             {% endif %}"
             href="{% url 'users:signup' %}">
            Регистрация
          </a>
        </li>
        {% endwith %}

        {% endif %}
      </ul>
      {# Конец добавленого в спринте #}
    </div>
  </nav>
</header>