yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="index"),
    path("group/<slug:slug>/", views.group_posts, name="group_list"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("posts/<int:post_id>/", views.post_detail, name="post_detail"),
    path("create/", views.post_create, name="post_create"),
    path("posts/<int:post_id>/edit/", views.post_edit, name="post_edit"),
    path("posts/<int:post_id>/comment", views.add_comment, name="add_comment"),
    path("follow/", views.follow_index, name="follow_index"),
    path("profile/<str:username>/follow/",
         views.profile_follow,
         name="profile_follow"),
    path(
        "profile/<str:username>/unfollow/",
        views.profile_unfollow,
        name="profile_unfollow",
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        "Группа", max_length=200, help_text="Добавьте название группы"
    )
    slug = models.SlugField("Слаг", unique=True, help_text="Добавьте слаг")
    description = models.TextField("Описание", help_text="Добавьте описание")

    class Meta:
        verbose_name = "Группа"
        verbose_name_plural = "Группы"

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField("Текст поста",
                            blank=False,
                            help_text="Введите тест поста")
    pub_date = models.DateTimeField(
        "Дата публикации",
        auto_now_add=True,
        help_text="Добавьте дату публикации"
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts",
        verbose_name="Автор",
        help_text="Впишите имя автора поста",
    )

    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="posts",
        verbose_name="Группа",
        help_text="Выберите группу",
    )

    image = models.ImageField("Картинка", upload_to="posts/", blank=True)

    class Meta:
        ordering = ["-pub_date"]
        verbose_name = "Пост"
        verbose_name_plural = "Посты"

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="Пост",
        help_text="Добавьте комментарий к посту",
    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="Автор",
        help_text="Впишите имя автора комментария",
    )

    text = models.TextField(
        "Текст комментария", blank=False, help_text="Введите тест комментария"
    )

    created = models.DateTimeField(
        "Дата комментария",
        auto_now_add=True,
        help_text="Добавьте дату коментария"
    )

    class Meta:
        ordering = ["-created"]
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

    def __str__(self):
        return self.text


class Follow(models.Model):
    #  кто подписывается
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="follower",
        verbose_name="Пользователь",
        help_text="Впишите имя пользователя",
    )
    #  на кого подписываются
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="following",
        verbose_name="Автор",
        help_text="Впишите имя автора",
        null=True,
    )

    class Meta:
        verbose_name = "Подписка"
        verbose_name_plural = "Подписки"

    def __str__(self):
        return str(self.author)

yatube/posts/forms.py
from django import forms
from django.forms import ModelForm

from .models import Comment, Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ("text", "group", "image")
        widgets = {
            "text": forms.Textarea(attrs={"rows": 10, "cols": 40}),
        }
        help_texts = {
            "text": "Текст нового поста",
            "group": "Группа, к которой будет относиться пост",
            "image": "Картинка",
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ("text",)
        widgets = {
            "text": forms.Textarea(attrs={"rows": 10, "cols": 40}),
        }
        help_texts = {
            "text": "Текст нового комментария",
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from yatube import settings

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, settings.PAGE_SIZE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "page_obj": page_obj,
    }
    return render(request, "posts/index.html", context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    paginator = Paginator(post_list, settings.PAGE_SIZE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "group": group,
        "page_obj": page_obj,
    }
    return render(request, "posts/group_list.html", context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    main_user = request.user
    post_list = author.posts.all()
    paginator = Paginator(post_list, settings.PAGE_SIZE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    post_number = post_list.count()
    follow = Follow.objects.filter(author=author.pk)
    following = True if follow else False
    context = {
        "main_user": main_user,
        "page_obj": page_obj,
        "post_number": post_number,
        "author": author,
        "following": following,
    }
    return render(request, "posts/profile.html", context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    user = get_object_or_404(User, username=post.author)
    post_number = user.posts.filter(author=user).count()
    comments = post.comments.all()
    form = CommentForm()
    context = {
        "post": post,
        "post_number": post_number,
        "post_id": post_id,
        "comments": comments,
        "form": form,
    }
    return render(request, "posts/post_detail.html", context)


@login_required
def post_create(request):

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect("posts:profile", username=post.author)

    return render(
        request, "posts/create_post.html",
        {"form": form, "username": request.user}
    )


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        raise Http404

    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect("posts:post_detail", post_id=post_id)

    return render(
        request,
        "posts/create_post.html",
        {"form": form, "username": request.user, "is_edit": True},
    )


@login_required
def add_comment(request, post_id):
    post = Post.objects.get(pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect("posts:post_detail", post_id=post_id)


@login_required
def profile_follow(request, username):
    # Подписаться на автора
    author = get_object_or_404(User, username=username)
    user = request.user
    if author != user and not (Follow.objects.filter(
            user=request.user, author=author).exists()):
        Follow.objects.get_or_create(user=user, author=author)
    return redirect("posts:profile", username=username)


@login_required
def profile_unfollow(request, username):
    # Дизлайк, отписка
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect("posts:profile", username=username)


@login_required
def follow_index(request):
    user = request.user
    author = user.follower.values_list("author", flat=True)
    post_list = Post.objects.filter(author__in=author)
    paginator = Paginator(post_list, settings.PAGE_SIZE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "page_obj": page_obj,
    }
    return render(request, "posts/follow.html", context)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}Новый пост{% endblock %}
{% block header %}Новый пост{% endblock %}
{% block content %}
  <main>
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-body">
              <div class="card-header">
                {% if is_edit %}
                  Редактировать запись
                {% else %}
                  Добавить запись
                {% endif %}
              </div>
              <form action="{% url 'posts:post_create' %}" method="post" enctype="multipart/form-data">
              {% csrf_token %}
                <div class="form-group row my-3 p-3">
                  <label for="id_text">Текст поста<span class="required text-danger" >*</span></label>
                  {{ form.text }}
                  <span class="helptext text-muted">Текст нового поста</span>
                </div>

                <div class="form-group row my-3 p-3">
                  <label for="id_group">Group</label>
                  {{ form.group }}
                  <span class="helptext text-muted">Группа, к которой будет относиться пост</span>
                </div>

                <div class="form-group row my-3 p-3">
                  <label for="id_image">Image</label>
                  {{ form.image }}
                  <span class="helptext text-muted">Изображение к посту</span>
                </div>

              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}Посты авторов, на которых подписан текущий пользователь{% endblock %}
{% block header %}Посты авторов, на которых подписан текущий пользователь{% endblock %}
{% block content %}
{% load thumbnail %}
    <div class="container">
        {% csrf_token %}
        {% include 'posts/includes/switcher.html' %}
        {% for post in page_obj %}
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text }}</p>
          {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
    </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}Записи сообщества{% endblock %}
{% block content %}
{% load thumbnail %}
  <div class="container" href="{% url 'posts:group_list' group.slug %}">
    <h1>{{ group.title }}</h1>
        <p>
          {{ group.description }}
        </p>
        {% for post in page_obj %}
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text }}</p>
          <hr>
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}
{% load cache %}
{% load thumbnail %}
    <div class="container">
        {% cache 20 index_page %}
        {% include 'posts/includes/switcher.html' %}
        {% for post in page_obj %}
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text }}</p>
          {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
        {% endcache %}
    </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% block title %} Пост {{ post.text|truncatewords:30 }} {% endblock %}
{% block content %}
{% load user_filters %}
{% load thumbnail %}
    <!-- Подключены иконки, стили и заполенены мета теги -->
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            <!-- если у поста есть группа -->
            {% if post.group %}
            Группа: {{ group.title }}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif %}
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора: <span>{{ post_number }}</span>
            </li>
            <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
           {{ post.text }}
          </p>
          {% if user == post.author %}
            <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
              редактировать запись
            </a>
          {% endif %}

        {% if user.is_authenticated %}
          <div class="card my-4">
            <h5 class="card-header">Добавить комментарий:</h5>
            <div class="card-body">
              <form method="post" action="{% url 'posts:add_comment' post.id %}">
                {% csrf_token %}
                <div class="form-group mb-2">
                  {{ form.text|addclass:"form-control" }}
                </div>
                <button type="submit" class="btn btn-primary">Отправить</button>
              </form>
            </div>
          </div>
        {% endif %}

        {% for comment in comments %}
          <div class="media mb-4">
            <div class="media-body">
              <h5 class="mt-0">
                <a href="{% url 'posts:profile' comment.author.username %}">
                 {{ comment.author.username }}
                </a>
              </h5>
                <p>
                 {{ comment.text }}
                </p>
              </div>
            </div>
        {% endfor %}
        </article>
      </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}Профайл пользователя {{ author.get_full_name }}{% endblock %}
{% block content %}
{% load user_filters %}
{% load thumbnail %}
      <div class="container py-5">
        <div class="mb-5">
        <h1>Все посты пользователя {{ author.get_full_name }} </h1>
        <h3>Всего постов: {{ post_number }} </h3>
        {% if main_user != author %}
          {% if following %}
            <a
              class="btn btn-lg btn-light"
              href="{% url 'posts:profile_unfollow' author.username %}" role="button"
            >
              Отписаться
            </a>
          {% else %}
            <a
              class="btn btn-lg btn-primary"
              href="{% url 'posts:profile_follow' author.username %}" role="button"
            >
              Подписаться
            </a>
          {% endif %}
        {% endif %}
        </div>
        {% for post in page_obj %}
        <article>
          <ul>
            <li>
              Автор: {{ author.get_full_name }}
              <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>

          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}

          <p>
          {{ post.text }}
          </p>
          <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
        </article>

        {% if post.group %}
        Группа: {{ group.title }}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}

        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
    </div>
{% endblock %}