yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'signup/',
        views.SignUp.as_view(template_name='users/signup.html'),
        name='signup'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    )
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yatube/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/users/logged_out.html
{# Это код файла templates/users/logged_out.html #}

{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block header %}Выход{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/login.html
# templates/users/login.html

{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block header %}Войти на сайт{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <!-- Тест на внимательность. Без переопределения шаблона этого адреса
            не существует. Нужно что-то делать, иначе все упадет -->
            <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/password_change_done.html
{# Это код файла templates/users/password_change_done.html #}

{% extends 'base.html' %}
{% block title %}Пароль изменён{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Пароль изменён
      </div>
      <div class="card-body">
        <p>Пароль изменён успешно</p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/password_change_form.html
{# Это код файла templates/users/password_change_form.html #}

{% extends 'base.html' %}
{% block title %}Изменение пароля{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Изменить пароль
        </div>
        <div class="card-body">
          <form method="post" action="../users/password_change_form.html">
            <input type="hidden" name="csrfmiddlewaretoken" value="">
            <div class="form-group row my-3 p-3">
              <label for="id_old_password">
                Старый пароль
                <span class="required text-danger">*</span>
              </label>
              <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_new_password1">
                Новый пароль
                <span class="required text-danger">*</span>
              </label>
              <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                <small id="id_new_password1-help" class="form-text text-muted">
                  <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li>
                    <li>Ваш пароль должен содержать как минимум 8 символов.</li>
                    <li>Ваш пароль не может быть одним из широко распространённых паролей.</li>
                    <li>Ваш пароль не может состоять только из цифр.</li>
                  </ul>
                </small>
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_new_password2">
                Подтверждение нового пароля
                <span class="required text-danger">*</span>
              </label>
              <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
            </div>
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Изменить пароль
              </button>
            </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
</div>
{% endblock %}

yatube/templates/users/password_reset_complete.html
{# Это код файла templates/users/password_reset_complete.html #}

{% extends 'base.html' %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Восстановление пароля завершено
        </div>
        <div class="card-body">
          <p>Ваш пароль был сохранен. Используйте его для входа</p>
          <a href="../users/login.html">войти</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{# Это код файла templates/users/password_reset_confirm.html #}

{% extends 'base.html' %}
{% block title %}Новый пароль{% endblock %}
{% block content %}
{% load user_filters %}

{% if validlink %}

<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Введите новый пароль
        </div>
        <div class="card-body">
          <form method="post" action="../users/password_reset_confirm.html">
            <input type="hidden" name="csrfmiddlewaretoken" value="">
            <div class="form-group row my-3 p-3">
              <label for="id_new_password1">
                Новый пароль
                <span class="required text-danger">*</span>
              </label>
              <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
              <small id="id_new_password1-help" class="form-text text-muted">
                <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li>
                  <li>Ваш пароль должен содержать как минимум 8 символов.</li>
                  <li>Ваш пароль не может быть одним из широко распространённых паролей.</li>
                  <li>Ваш пароль не может состоять только из цифр.</li>
                </ul>
              </small>
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_new_password2">
                Подтверждение нового пароля
                <span class="required text-danger">*</span>
              </label>
              <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
            </div>
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Назначить новый пароль
              </button>
            </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
  <!-- если использована неправильная ссылка -->
{% else %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Ошибка</div>
      <div class="card-body">
        <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endif %}
  <!-- конец если использована неправильная ссылка -->
</div>
{% endblock %}

yatube/templates/users/password_reset_done.html
{# Это код файла templates/users/password_reset_done.html #}

{% extends 'base.html' %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Отправлено письмо
        </div>
        <div class="card-body">
          <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/password_reset_form.html
{# Это код файла templates/users/password_reset_done.html #}

{% extends 'base.html' %}
{% block title %}Сброс пароля{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
        </div>
        <div class="card-body">
          <form method="post" action="../users/password_reset_form.html">
            <input type="hidden" name="csrfmiddlewaretoken" value="">
            <div class="form-group row my-3 p-3">
              <label for="id_email">
                Адрес электронной почты
                <span class="required text-danger">*</span>
              </label>
              <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
            </div>
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Сбросить пароль
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block header %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
          <div class="card-body">
          {% load user_filters %} {# Загружаем фильтры #}
              {% if form.errors %}
                  {% for field in form %}
                    {% for error in field.errors %}
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post"
                {% if action_url %}
                  action="{% url action_url %}"
                {% endif %}
              >
              {% csrf_token %}

              {# Выводим поля в цикле, по отдельности #}
              {% for field in form %}
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  <div>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                      <small
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                  </div>
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}